siriwatknp/mui-treasury

src/components/tabs/ElevatedTabs.js
src/components/tabs/PillsTabs.js
src/pages/components/TabsPage.js

I've created another component in Tab Section. I have already provided the example code on codesandbox.com
I hope you like it

(New) ElevatedTabs, PillsTabs

---

package.json
src/components/peapods/PeaMediaUploader.js
src/pages/brands/PeapodsPage.js
yarn.lock

You cannot actually upload files to the server, as it requires a backend api for signing the uploads.
This is just the pure component.
There are some non-urgent TODOs that will need to be addressed in the future.

implement PeaMediaUploader

---

src/components/peapods/PeaMediaUploader.js

Using NODE_PATH does not work when using this as a git submodule.

use relative import path

---

src/components/peapods/PeaThreadHeader.js
src/pages/brands/PeapodsPage.js

ThreadHeader

---

package.json
src/components/peapods/PeaMessageInput.js
src/components/peapods/PeaThreadHeader.js
src/pages/brands/PeapodsPage.js
yarn.lock

Message input

---

src/components/peapods/PeaThreadTitle.js
src/pages/brands/PeapodsPage.js

Thread title

---

src/components/peapods/PeaToast.js

implement toast pure component for peapods

implement toast pure component for peapods

---

src/components/peapods/PeaTrendingHashtagList.js

implement trending hashtag list pure component for peapods

implement trending hashtag list pure component for peapods

---

src/pages/Layout/GetCode.js

fix name of ChevronRightIcon

---

src/components/molecules/Timeline.js
src/demoPages/Amigo/AmigoHome.js
src/demoPages/Amigo/components/BrandPicker.js
src/demoPages/Amigo/components/CategoryPicker.js
src/demoPages/Amigo/components/ColorPicker.js
src/demoPages/Amigo/components/Expander.js
src/demoPages/Amigo/components/MegaMenu.js
src/demoPages/Amigo/components/PricePicker.js
src/demoPages/Amigo/components/ProductAds.js
src/demoPages/Amigo/components/ProductCard.js
src/demoPages/Amigo/components/SizePicker.js
src/demoPages/Amigo/theme/components/container.js
src/pages/TimelinePage.js

#42 template amigo e commerce

---

src/brands/peapods/PeapodsPage.js
src/brands/peapods/demo/GroupCard.js
src/brands/peapods/index.js
src/brands/peapods/lib/PeaGroupCard.js

Implement GroupCard pure component

[#116] add GroupCard

---

src/components/organisms/ComponentInfo.js
src/constant.js
src/docs/components/tabs/chromeTabsDoc.js
src/theme/treasury/treasuryTheme.js

fix bugs how to & add sandbox base template

---

src/components/tabs/SerratedTabs.js
src/docs/components/tabs/index.js
src/docs/components/tabs/serratedTabsDoc.js
src/pages/components/TabsPage.js

complete SerratedTabs

---

src/brands/peapods/PeapodsPage.js
src/brands/peapods/demo/AutocompleteHashtags.js
src/brands/peapods/demo/AutocompleteList.js
src/brands/peapods/lib/PeaAutocompleteList.js
src/brands/peapods/lib/PeaSearchInputControl.js
src/brands/peapods/lib/PeaTag.js
src/brands/peapods/lib/theme/components/peaChip.js

1. Implement AutocompleteHashtags smart component,
2. Fix autocomplete, input and tag pure components

[#126] - implement AutocompleteHashtags

---

package.json
src/brands/peapods/demo/AudienceSelector.js
src/brands/peapods/demo/AutocompleteHashtags.js
src/brands/peapods/demo/AutocompleteList.js
src/brands/peapods/demo/Tag.js
src/brands/peapods/lib/PeaAutocompleteList.js
src/brands/peapods/lib/PeaSearchInputControl.js
yarn.lock

This component can now handle more use-cases and looks better.

make PeaAutocompleteList more robust

---

src/brands/peapods/lib/PeaAccountProfile.js
src/brands/peapods/lib/PeaProfileEditor.js

refactor for profile photo uploading

---

src/brands/peapods/lib/PeaAccountProfile.js
src/brands/peapods/lib/PeaConfirmation.js
src/brands/peapods/lib/PeaProfileEditor.js
src/brands/peapods/lib/PeaUserSettings.js

update peopods components to delete account

delete profile in peapods

---

src/brands/peapods/lib/PeaAccountProfile.js
src/brands/peapods/lib/PeaGroupCard.js
src/brands/peapods/lib/PeaGroupDialog.js
src/brands/peapods/lib/PeaRadioGroup.js
src/brands/peapods/lib/theme/components/peaDialog.js

https://github.com/peapods/peapods.com/issues/57

CRUD-Group in peapods

---

package.json
src/brands/peapods/lib/PeaEventCard.js
src/brands/peapods/lib/PeaShareContent.js
yarn.lock

https://github.com/peapods/peapods.com/issues/69

add share buttons in event card

---

src/brands/peapods/lib/PeaGroupCard.js
src/brands/peapods/lib/theme/components/peaDialog.js

https://github.com/peapods/peapods.com/issues/86
https://github.com/peapods/peapods.com/issues/70

refactor PeaGroupCard component

---

src/brands/peapods/lib/PeaAutocompleteList.js
src/brands/peapods/lib/PeaMenuItem.js
src/brands/peapods/lib/theme/components/peaInputBase.js

refactor Pea components for search UX

---

src/brands/peapods/lib/PeaAccountProfile.js
src/brands/peapods/lib/PeaAvatar.js
src/brands/peapods/lib/PeaFullProfile.js
src/brands/peapods/lib/PeaInvitationDialog.js
src/brands/peapods/lib/theme/components/peaDialog.js

https://github.com/peapods/peapods.com/issues/70 ( group invitation )
https://github.com/peapods/peapods.com/issues/84 ( follow user )

invite users to group and follow users in peapods

---

src/components/molecules/GridShowcase.js
src/components/organisms/CustomComponentGrid.js
src/containers/Demo/DemoComponents.js
src/containers/Demo/DemoSourceDrawer.js
src/docs/components/card/blog/BlogCard.js
src/docs/components/card/kanban/KanbanCard.js
src/docs/components/card/review2/ReviewCard2.js
src/docs/components/card/reward/RewardCard.js
src/docs/components/grid/fullBordered/FullBorderedGrid.js
src/docs/components/grid/gutterBordered/GutterBorderedGrid.js
src/docs/components/grid/halfBordered/HalfBorderedGrid.js
src/docs/components/tabs/chrome/ChromeTabs.js
src/docs/components/tabs/contained/ContainedTabs.js
src/docs/components/tabs/elevated/ElevatedTabs.js
src/docs/components/tabs/firebase/FirebaseTabs.js
src/docs/components/tabs/instagram/InstagramTabs.js
src/docs/components/tabs/pill/PillTabs.js
src/docs/components/tabs/plain/PlainTabs.js
src/docs/components/tabs/serrated/SerratedTabs.js
src/docs/components/tabs/twitter/TwitterTabs.js
src/docs/components/tabs/twitterIcon/TwitterIconTabs.js
src/pages/components/tabs.js

refac metadata

---

CONTRIBUTING.md

- Add syntax highlighting for code snippets
- Capitialize headers (for consistency with other headers)

Improve CONTINBUTING.md

---

packages/mui-styles/src/tabs/index.js
packages/mui-styles/src/tabs/inside-triangle/index.js
packages/mui-styles/src/tabs/inside-triangle/insideTriangleTabs.styles.js
src/docs/components/tabs/inside-triangle/InsideTriangleTabs.js
src/docs/components/tabs/inside-triangle/index.md

Issue #155 
Todo: Fix ripple's shape

create InsideTriangleTabs component

---

src/docs/components/tag/insideLeftLine/InsideLeftLineTag.js
src/docs/components/tag/insideLeftLine/index.md

issue: #157 
Create inside left line tag component

[Component] Create InsideLeftLineTag component

---

MIGRATION.md
src/constants/mock.js
src/docs/components/arrow/simple/SimpleArrow.js
src/docs/components/card/planeTicket/PlaneTicketCard.js
src/docs/components/card/planeTicket/index.md
src/docs/components/card/review2/ReviewCard2.js

demo in Hacktober Fest BKK 2019 by me
https://codesandbox.io/s/centering-in-css-fy1bm

Publish AirplaneTicketCard

---

packages/mui-styles/src/arrow/index.js
packages/mui-styles/src/arrow/inverted/index.js
packages/mui-styles/src/arrow/inverted/invertedArrow.styles.js
packages/mui-styles/src/arrow/simple/index.js
packages/mui-styles/src/arrow/simple/simpleArrow.styles.js
src/docs/components/arrow/inverted/InvertedArrow.js
src/docs/components/arrow/inverted/index.md
src/docs/components/arrow/simple/index.md
src/docs/components/card/planeTicket/PlaneTicketCard.js
src/docs/components/rip/vertical/VerticalRip.js

complete simple & inverted arrow

---

MIGRATION.md
packages/mui-styles/src/arrow/index.js
packages/mui-styles/src/arrow/inverted/index.js
packages/mui-styles/src/arrow/inverted/invertedArrow.styles.js
packages/mui-styles/src/arrow/simple/index.js
packages/mui-styles/src/arrow/simple/simpleArrow.styles.js
packages/mui-styles/src/rip/index.js
packages/mui-styles/src/rip/vertical/index.js
packages/mui-styles/src/rip/vertical/verticalRip.styles.js
src/components/molecules/GridShowcase.js
src/components/organisms/CustomComponentGrid.js
src/constants/menus.js
src/constants/mock.js
src/containers/Demo/DemoComponents.js
src/containers/Demo/context/metadataContext.js
src/docs/components/arrow/inverted/InvertedArrow.js
src/docs/components/arrow/inverted/index.md
src/docs/components/arrow/simple/index.md
src/docs/components/card/planeTicket/PlaneTicketCard.js
src/docs/components/card/review2/ReviewCard2.js
src/docs/components/rip/index.js
src/docs/components/rip/vertical/VerticalRip.js
src/docs/components/rip/vertical/index.md
src/pages/components/rip.js

Migrate arrow

---

packages/mui-styles/src/tag/flexy/flexyTag.styles.js
packages/mui-styles/src/tag/flexy/index.js
packages/mui-styles/src/tag/index.js
src/docs/components/tag/flexy/FlexyTag.js
src/docs/components/tag/flexy/index.md

complete FlexyTag

---

packages/mui-components/src/cardHeader/brand/BrandCardHeader.js
packages/mui-components/src/indicator/dot/DotIndicator.js
packages/mui-components/src/indicator/dot/index.js
packages/mui-components/src/indicator/index.js
packages/mui-styles/src/indicator/dot/dotIndicator.styles.js
packages/mui-styles/src/indicator/dot/index.js
packages/mui-styles/src/indicator/index.js
packages/mui-styles/src/indicator/inverted/index.js
packages/mui-styles/src/indicator/inverted/invertedIndicator.styles.js
src/docs/components/indicator/dot/DotIndicatorDemo.js
src/docs/components/indicator/dot/index.md
src/docs/components/indicator/inverted/InvertedIndicatorDemo.js
src/docs/components/indicator/inverted/index.md

complete indicator

---

packages/mui-styles/src/input/bootstrap/bootstrapInput.styles.js
packages/mui-styles/src/input/bootstrap/index.js
packages/mui-styles/src/input/chrome/chromeInput.styles.js
packages/mui-styles/src/input/chrome/index.js
packages/mui-styles/src/input/index.js
packages/mui-styles/src/input/search/index.js
packages/mui-styles/src/input/search/searchInput.styles.js
src/docs/components/input/bootstrap/BootstrapInput.js
src/docs/components/input/bootstrap/index.md
src/docs/components/input/chrome/ChromeInput.js
src/docs/components/input/chrome/index.md
src/docs/components/input/search/SearchInput.js
src/docs/components/input/search/index.md

- fix #171
- fix #172 
- fix #173

complete input components

---

packages/mui-styles/src/textField/bootstrap/bootstrapTextField.styles.js
packages/mui-styles/src/textField/bootstrap/index.js
packages/mui-styles/src/textField/filled/filledTextField.styles.js
packages/mui-styles/src/textField/filled/index.js
packages/mui-styles/src/textField/index.js
src/docs/components/textField/bootstrap/BootstrapTextField.js
src/docs/components/textField/bootstrap/index.md
src/docs/components/textField/filled/FilledTextField.js
src/docs/components/textField/filled/index.md

#175 component textfields

---

src/docs/components/card/pricing/PricingCard.js
src/docs/components/card/pricing/index.md

- Add simple pricing card component

Add pricing card

---

website/package.json
website/src/__temporary__/ContentForm.js
website/src/__temporary__/FooterForm.js
website/src/__temporary__/GetCode.js
website/src/__temporary__/HeaderForm.js
website/src/__temporary__/IconForm.js
website/src/__temporary__/Intro.js
website/src/__temporary__/LayoutBuilderPage.js
website/src/__temporary__/NavForm.js
website/src/__temporary__/Row.js
website/src/components/atoms/Box.js
website/src/components/extensions/Button.js
website/src/components/extensions/Icon.js
website/src/components/molecules/Prism.js
website/src/components/molecules/PrismWithCopier.js
website/src/components/organisms/ModuleProjector.js
website/src/pages/layout/builder.js
yarn.lock

complete layout builder v2

---

packages/mui-components/src/menuList/HorzMenuList/HorzMenuList.js
website/src/components/layout/Header.js
website/src/components/molecules/Prism.js
website/src/components/section/StylingIsFun.js
website/src/docs/components/card/kanban/KanbanCard.js
website/src/pages/index.js

complete & fix header overflow issue

---

website/src/components/section/StylingIsFun.js

Since it is a really really small bug fix, I did not open issue for it.
It is for just fixing the warning shown below

refs #0 tiny bug fix

---

packages/mui-layout/README.md

chore: 🤖 update readme

---

website/src/components/atoms/Copier.js
website/src/components/molecules/Html.js
website/src/containers/Demo/DemoSourceDrawer.js
website/src/containers/FrontMatter.js
website/src/containers/SourceFileDrawer.js
website/src/docs/layout/presets/muiTreasury/index.js
website/src/pages/layout/presets/mui-treasury.js

fix: 🐛 bug copier & bug frontmatter component

---

website/src/App.js
website/src/components/layout/Browser.js
website/src/components/layout/PageHeader.js
website/src/components/layout/PageLayout.js
website/src/modules/path/Path.js

Fix bugs website

---

website/src/__temporary__/GetCode.js

fix: 🐛 old layout builder to use v3.1 code

---

packages/mui-styles/src/cardContent/tag/index.js
packages/mui-styles/src/cardContent/tag/tagCard.styles.js
website/src/docs/components/card/tag/TagCard.js
website/src/docs/components/card/tag/index.md

I'm not sure if the place or naming of file is reasonable.  
@siriwatknp If you could review, I'm so glad!

#213 add tag card style

---

website/gatsby-config.js
website/package.json
yarn.lock

fix: 🐛 remove offline due to content missing & update manifest

☄️ Release site v1.5.2

---

scripts/copy-files.js

To resolve #257 
@siriwatknp Can it achieve what you wanted? 
Please let me know if there is any misunderstanding 🐕

refs #257 copy read me

---

.eslintrc
packages/mui-layout/src/__tests__/models/insetSidebar.test.js
packages/mui-layout/src/components/internal/SharedInsetSidebar.js
packages/mui-layout/src/models/insetSidebar.js
packages/mui-layout/src/utils/ConfigGenerator/SidebarGenerator.js
packages/mui-mockup/src/brands/dailyShopping/DailyCart.js
packages/mui-mockup/src/brands/dailyShopping/DailyCheckout.js
packages/mui-mockup/src/brands/dailyShopping/DailyHeader.js
packages/mui-mockup/src/brands/dailyShopping/DailyInteger.js
packages/mui-mockup/src/brands/dailyShopping/DailyLogo.js
packages/mui-mockup/src/brands/dailyShopping/DailySearch.js
packages/mui-mockup/src/brands/dailyShopping/DailySizeSelector.js
packages/mui-mockup/src/brands/dailyShopping/DailySummary.js
packages/mui-mockup/src/brands/dailyShopping/dailyShoppingTheme.js
packages/mui-mockup/src/brands/dailyShopping/index.js
website/src/constants/menus.js
website/src/docs/layout/clones/shoppingCart/ShoppingCartDemo.js
website/src/docs/layout/clones/shoppingCart/index.js
website/src/docs/layout/clones/shoppingCart/index.md
website/src/pages/layout/clones/shopping-cart.js

#369 cart layout clone

---

website/src/docs/layout/clones/shoppingCart/ShoppingCartDemo.js

fix: 🐛 Shopping clone ios bugs

---

packages/mui-components/package.json
packages/mui-layout/package.json
packages/mui-layout/src/__tests__/models/container.test.js
packages/mui-layout/src/__tests__/models/content.test.js
packages/mui-layout/src/__tests__/models/edgeEffect.test.js
packages/mui-layout/src/__tests__/models/footer.test.js
packages/mui-layout/src/__tests__/models/header.test.js
packages/mui-layout/src/__tests__/utils.test.js
packages/mui-layout/src/models/container.js
packages/mui-layout/src/models/content.js
packages/mui-layout/src/models/edgeEffect.js
packages/mui-layout/src/models/footer.js
packages/mui-layout/src/models/header.js
packages/mui-layout/src/models/width.js
packages/mui-layout/src/utils/combineMargin.js
packages/mui-layout/src/utils/toValidCssValue.js
packages/mui-mockup/package.json
packages/mui-styles/package.json
packages/mui-utils/package.json
website/src/docs/layout/clones/shoppingCart/ShoppingCartDemo.js
website/src/pages/layout/develop.js
yarn.lock

fix: 🐛 Shopping clone ios bugs

☄️ Release site v1.6.1

---

packages/mui-layout/src/__tests__/content.test.js
packages/mui-layout/src/__tests__/footer.test.js
packages/mui-layout/src/__tests__/header.test.js
packages/mui-layout/src/__tests__/secondarySidebar.test.js
packages/mui-layout/src/__tests__/sidebar.test.js
packages/mui-layout/src/components/Footer.js
packages/mui-layout/src/components/Header.js
packages/mui-layout/src/components/HeaderOffset.js
packages/mui-layout/src/components/internal/SharedSidebar.js

fix: 🐛 empty config error and add more tests to cover

---

website/src/components/organisms/ModuleProjector.js
website/src/constants/menus.js
website/src/global.css
website/src/modules/path/Path.js
website/src/pages/layout/tutorials/blog-layout.md
website/src/pages/layout/tutorials/dashboard-layout.md

docs: ✏️ add blog layout tutorial

---

website/gatsby-config.js
website/package.json
website/src/modules/path/Path.js
yarn.lock

fix: 🐛 add gatsby-plugin-catch-links for markdown

---

packages/mui-styles/src/tabs/inside-triangle/insideTriangleTabs.styles.js
website/src/components/layout/BrowserIFrame.js
website/src/components/layout/PageFooter.js
website/src/components/molecules/ShowcaseWidget.js
website/src/components/organisms/DefaultSection.js
website/src/containers/Demo/DemoSourceDrawer.js
website/src/docs/components/card/blog/BlogCard.js
website/src/docs/components/card/engagement/EngagementCard.js
website/src/docs/components/card/news/NewsCard.js
website/src/docs/components/card/project/ProjectCard.js
website/src/docs/components/carousel/parallax/ParallaxCarousel.js

feat: 🎸 add responsive view to components

---

packages/mui-styles/src/tabs/apple/appleTabs.styles.js
packages/mui-styles/src/tabs/apple/index.js
packages/mui-styles/src/tabs/index.js
website/src/__stories__/atoms.stories.js
website/src/__stories__/molecules.stories.js
website/src/components/atoms/StatusChip.js
website/src/components/molecules/GridShowcase.js
website/src/components/molecules/ShowcaseWidget.js
website/src/docs/components/button/firebase/FirebaseBtn.js
website/src/docs/components/tabs/apple/AppleTabs.js
website/src/docs/components/tabs/apple/index.md
website/src/utils/functions.js

- AppleTabs
- add new release badge to showcase widget

#452 apple tabs

---

package.json
packages/mui-styles/src/tabs/apple/appleTabs.styles.js
packages/mui-styles/src/tabs/apple/index.js
packages/mui-styles/src/tabs/index.js
website/src/__stories__/atoms.stories.js
website/src/__stories__/molecules.stories.js
website/src/components/atoms/StatusChip.js
website/src/components/molecules/GridShowcase.js
website/src/components/molecules/ShowcaseWidget.js
website/src/docs/components/button/firebase/FirebaseBtn.js
website/src/docs/components/tabs/apple/AppleTabs.js
website/src/docs/components/tabs/apple/index.md
website/src/utils/functions.js
yarn.lock

☄️ Release site v1.11.0

---

CHANGELOG.md
website/src/components/molecules/ShowcaseWidget.js
website/src/containers/Demo/DemoSourceDrawer.js
website/src/pages/layout/develop.js
website/src/utils/functions.js
website/src/utils/functions.spec.js

fix: 🐛 remove hide section in source

---

.storybook/webpack.config.js
website/gatsby-config.js
website/src/components/atoms/CarbonAds.css
website/src/components/atoms/CarbonAds.js
website/src/components/organisms/SloganSection.js
website/src/logics/useCarbonAds.js
website/src/logics/useScript.js

☄️ Release site v1.13.0

---

website/src/logics/useScript.js

☄️ Release site v1.13.1

---

website/src/components/atoms/CarbonAds.js
website/src/logics/useCarbonAds.js
website/src/logics/useScript.js

fix: 🐛 append script to document.body instead

☄️ Release site v1.13.2

---

website/gatsby-config.js
website/package.json
website/src/components/organisms/TopicSection.js
website/src/constants/menus.js
website/src/pages/index.js
yarn.lock

fix: 🐛 display only 1 ads per page

☄️ Release site v1.13.4

---

.storybook/config.js
_templates/treasury/component/index.ejs.t
_templates/treasury/component/prompt.js
_templates/treasury/component/react.ejs.t
_templates/treasury/component/stories.ejs.t
_templates/treasury/component/test.ejs.t
packages/mui-components/src/textField/birthday/BirthdayContext.js
packages/mui-components/src/textField/birthday/BirthdayTextField.js
packages/mui-components/src/textField/birthday/BirthdayTextField.stories.js
packages/mui-components/src/textField/birthday/BirthdayTextField.test.js
packages/mui-components/src/textField/birthday/index.js
packages/mui-components/src/textField/birthday/submodules/DayInput.js
packages/mui-components/src/textField/birthday/submodules/MonthInput.js
packages/mui-components/src/textField/birthday/submodules/Separator.js
packages/mui-components/src/textField/birthday/submodules/YearInput.js
packages/mui-components/src/textField/birthday/submodules/createInput.js
website/src/docs/components/textField/birthday/BirthdayTextField.js
website/src/docs/components/textField/birthday/index.md

[New] Component - BirthdayTextField

---

packages/mui-components/package.json
packages/mui-components/src/textField/birthday/BirthdayContext.js
yarn.lock

☄️ Release site v1.14.1

---

_templates/showcase/component/page.ejs.t
_templates/showcase/component/rootIndex.ejs.t
packages/mui-components/src/chart/org/OrgChart.js
packages/mui-components/src/chart/org/OrgChart.stories.js
packages/mui-components/src/chart/org/OrgChart.test.js
packages/mui-components/src/chart/org/index.js
packages/mui-components/src/chart/org/orgChart.styles.js
website/src/constants/menus.js
website/src/docs/components/chart/index.js
website/src/docs/components/chart/org/OrgChart.js
website/src/docs/components/chart/org/index.md
website/src/docs/components/textField/birthday/BirthdayTextField.js
website/src/pages/components/chart.js

[New] Component - OrgChart

---

packages/mui-styles/src/shadow/neumorph/index.js
packages/mui-styles/src/shadow/neumorph/neumorphShadow.styles.js
website/package.json
website/src/docs/components/shadow/neumorph/NeumorphShadow.js
website/src/docs/components/shadow/neumorph/index.md
yarn.lock

feat: 🎸 add neumorph shadow

---

packages/mui-components/src/chart/family/familyChart.styles.js
packages/mui-styles/src/shadow/neumorph/index.js
packages/mui-styles/src/shadow/neumorph/neumorphShadow.styles.js
website/package.json
website/src/docs/components/shadow/neumorph/NeumorphShadow.js
website/src/docs/components/shadow/neumorph/index.md
yarn.lock

☄️Release site v1.17.0

---

website/src/docs/components/shadow/neumorph/NeumorphShadow.js

☄️ Release site v1.17.2

---

_templates/showcase/component/categoryPage.ejs.t
_templates/showcase/component/componentPage.ejs.t
_templates/showcase/component/react.ejs.t
packages/mui-styles/src/shadow/neumorph/neumorphShadow.styles.js
website/gatsby-node.js
website/src/components/atoms/CarbonAds.js
website/src/components/molecules/BtnGroup.js
website/src/components/molecules/GridShowcase.js
website/src/constants/menus.js
website/src/containers/Showcase/ComponentShowcase.js
website/src/docs/components/chart/family/FamilyChart.js
website/src/docs/components/textField/birthday/BirthdayTextField.js
website/src/logics/useScreenList.js
website/src/modules/path/Path.js
website/src/pages/components/chart/family/index.js
website/src/pages/components/chart/org/index.js
website/src/pages/components/chart/tree/index.js
website/src/pages/components/text-field/birthday/index.js
website/src/utils/functions.js
website/src/utils/theme.js

#498 new component page layout

---

_templates/showcase/component/categoryPage.ejs.t
_templates/showcase/component/componentPage.ejs.t
_templates/showcase/component/react.ejs.t
packages/mui-styles/src/shadow/neumorph/neumorphShadow.styles.js
website/gatsby-node.js
website/src/components/atoms/CarbonAds.js
website/src/components/molecules/BtnGroup.js
website/src/components/molecules/GridShowcase.js
website/src/constants/menus.js
website/src/containers/Showcase/ComponentShowcase.js
website/src/docs/components/chart/family/FamilyChart.js
website/src/docs/components/shadow/neumorph/NeumorphShadow.js
website/src/docs/components/textField/birthday/BirthdayTextField.js
website/src/logics/useScreenList.js
website/src/modules/path/Path.js
website/src/pages/components/chart/family/index.js
website/src/pages/components/chart/org/index.js
website/src/pages/components/chart/tree/index.js
website/src/pages/components/text-field/birthday/index.js
website/src/utils/functions.js
website/src/utils/theme.js

☄️ Release site v1.18.0

---

CHANGELOG.md
packages/mui-components/package.json
packages/mui-mockup/package.json
packages/mui-styles/package.json
website/gatsby-node.js
website/package.json

☄️ Release site v1.18.1

---

packages/mui-styles/src/switch/ios/index.js
packages/mui-styles/src/switch/ios/iosSwitch.styles.js
website/src/constants/menus/styleMenus.js
website/src/docs/styles/switch/index.js
website/src/docs/styles/switch/ios/IosSwitchStyle.js
website/src/docs/styles/switch/ios/index.js
website/src/docs/styles/switch/ios/index.md
website/src/pages/styles/switch.js
website/src/pages/styles/switch/ios/index.js

feat: 🎸 complete ios switch style

---

CHANGELOG.md
packages/mui-components/package.json
packages/mui-mockup/package.json
packages/mui-styles/package.json
packages/mui-styles/src/switch/ios/index.js
packages/mui-styles/src/switch/ios/iosSwitch.styles.js
packages/mui-utils/package.json
website/package.json
website/src/constants/menus/styleMenus.js
website/src/docs/styles/switch/index.js
website/src/docs/styles/switch/ios/IosSwitchStyle.js
website/src/docs/styles/switch/ios/index.js
website/src/docs/styles/switch/ios/index.md
website/src/pages/styles/switch.js
website/src/pages/styles/switch/ios/index.js

☄️ Release site v1.22.0

---

_templates/showcase/style/react.ejs.t
packages/mui-styles/src/switch/ios/iosSwitch.styles.js
packages/mui-styles/src/switch/lovely/index.js
packages/mui-styles/src/switch/lovely/lovelySwitch.styles.js
website/src/docs/styles/switch/lovely/LovelySwitchStyle.js
website/src/docs/styles/switch/lovely/index.js
website/src/docs/styles/switch/lovely/index.md
website/src/pages/styles/switch/lovely/index.js

feat: 🎸 complete lovelySwitch style and fix hygen template

---

packages/mui-styles/src/switch/ios/index.js
packages/mui-styles/src/switch/ios/iosSwitch.styles.js
website/src/constants/menus/styleMenus.js
website/src/docs/styles/switch/index.js
website/src/docs/styles/switch/ios/IosSwitchStyle.js
website/src/docs/styles/switch/ios/index.js
website/src/docs/styles/switch/ios/index.md
website/src/pages/styles/switch.js
website/src/pages/styles/switch/ios/index.js

☄️ Release site v1.22.1

---

packages/mui-styles/src/switch/n02/index.js
packages/mui-styles/src/switch/n02/n02Switch.styles.js
website/src/docs/styles/switch/n02/N02SwitchStyle.js
website/src/docs/styles/switch/n02/index.js
website/src/docs/styles/switch/n02/index.md
website/src/pages/styles/switch/n02/index.js

feat: 🎸 add switch II style

---

packages/mui-styles/src/switch/n01/index.js
packages/mui-styles/src/switch/n01/n01Switch.styles.js
website/src/docs/styles/switch/n01/N01SwitchStyle.js
website/src/docs/styles/switch/n01/index.js
website/src/docs/styles/switch/n01/index.md
website/src/pages/styles/switch/n01/index.js

feat: 🎸 add Switch I style & showcase

---

website/src/docs/components/carousel/parallax/ParallaxCarousel.js

fix: 🐛 update path

---

packages/mui-styles/src/inputBase/bordered/borderedInputBase.styles.js
packages/mui-styles/src/inputBase/bordered/index.js
packages/mui-styles/src/textField/bordered/borderedTextField.styles.js
packages/mui-styles/src/textField/bordered/index.js
website/src/constants/menus/styleMenus.js
website/src/docs/styles/inputBase/bordered/BorderedInputBaseStyle.js
website/src/docs/styles/inputBase/bordered/index.js
website/src/docs/styles/inputBase/bordered/index.md
website/src/docs/styles/textField/bordered/BorderedTextFieldStyle.js
website/src/docs/styles/textField/bordered/index.js
website/src/docs/styles/textField/bordered/index.md
website/src/pages/styles/input-base/bordered/index.js
website/src/pages/styles/text-field/bordered/index.js

#531 border input text field

---

packages/mui-styles/src/inputBase/bordered/borderedInputBase.styles.js
packages/mui-styles/src/inputBase/round/index.js
packages/mui-styles/src/inputBase/round/roundInputBase.styles.js
packages/mui-styles/src/textField/round/index.js
packages/mui-styles/src/textField/round/roundTextField.styles.js
website/src/docs/styles/inputBase/round/RoundInputBaseStyle.js
website/src/docs/styles/inputBase/round/index.js
website/src/docs/styles/inputBase/round/index.md
website/src/docs/styles/textField/round/RoundTextFieldStyle.js
website/src/docs/styles/textField/round/index.js
website/src/docs/styles/textField/round/index.md
website/src/pages/styles/input-base/round/index.js
website/src/pages/styles/text-field/round/index.js

feat: 🎸 add round input & textField style

---

packages/mui-styles/src/inputBase/round/roundInputBase.styles.js
packages/mui-styles/src/textField/round/roundTextField.styles.js
website/src/docs/styles/textField/round/RoundTextFieldStyle.js

- add support for secondary color

#532 round input textfield

---

packages/mui-styles/src/checkbox/banner/bannerCheckbox.styles.js
packages/mui-styles/src/checkbox/banner/index.js
website/src/components/layout/PageLayout.js
website/src/constants/menus/styleMenus.js
website/src/docs/styles/checkbox/banner/BannerCheckboxStyle.js
website/src/docs/styles/checkbox/banner/index.js
website/src/docs/styles/checkbox/banner/index.md
website/src/docs/styles/checkbox/index.js
website/src/pages/styles/checkbox.js

package @mui-treasury/styles
✅ Closes: #537

feat: 🎸 #537 add BannerCheckboxStyle

---

packages/mui-styles/src/checkbox/neon/index.js
packages/mui-styles/src/checkbox/neon/neonCheckbox.styles.js
packages/mui-styles/src/radio/neon/index.js
packages/mui-styles/src/radio/neon/neonRadio.styles.js
website/src/components/layout/PageLayout.js
website/src/constants/menus/styleMenus.js
website/src/docs/styles/checkbox/neon/NeonCheckboxStyle.js
website/src/docs/styles/checkbox/neon/index.js
website/src/docs/styles/checkbox/neon/index.md
website/src/docs/styles/radio/index.js
website/src/docs/styles/radio/neon/NeonRadioStyle.js
website/src/docs/styles/radio/neon/index.js
website/src/docs/styles/radio/neon/index.md
website/src/pages/styles/radio.js

🎸 #538 NeonCheckbox & NeonRadio style

---

packages/mui-styles/src/checkbox/neon/index.js
packages/mui-styles/src/checkbox/neon/neonCheckbox.styles.js
packages/mui-styles/src/radio/neon/index.js
packages/mui-styles/src/radio/neon/neonRadio.styles.js
website/src/components/layout/PageLayout.js
website/src/constants/menus/styleMenus.js
website/src/docs/styles/checkbox/neon/NeonCheckboxStyle.js
website/src/docs/styles/checkbox/neon/index.js
website/src/docs/styles/checkbox/neon/index.md
website/src/docs/styles/radio/index.js
website/src/docs/styles/radio/neon/NeonRadioStyle.js
website/src/docs/styles/radio/neon/index.js
website/src/docs/styles/radio/neon/index.md
website/src/pages/styles/radio.js

* feat: 🎸 #538 add NeonCheckbox style
* feat: 🎸 #538 add NeonRadio style
✅ Closes: #538

☄️ Release site v1.24.0

---

packages/mui-styles/src/switch/airbnb/airbnbSwitch.styles.js
packages/mui-styles/src/switch/airbnb/index.js
packages/mui-styles/src/switch/lovely/lovelySwitch.styles.js
website/src/docs/styles/switch/airbnb/AirbnbSwitchStyle.js
website/src/docs/styles/switch/airbnb/index.js
website/src/docs/styles/switch/airbnb/index.md

feat: 🎸 #546 add AirbnbSwitch style

---

packages/mui-layout/package.json
scripts/copy-files.js

[#624] fix: 🐛 add typescriptCopy to copy-files script

---

website/src/components/layout/PageLayout.js
website/src/docs/layout/clones/reactjs/ReactJsDemo.js

[#650] fix: 🐛 ReactJs layout crash and bgcolor at content

---

website/src/components/layout/PageLayout.js

☄️ Release site v1.25.2

---

website/src/containers/Demo/DemoSourceDrawer.js
website/src/pages/components/index.mdx

These small doc changes should make it a little easier for first time users to use mui-treasury.

#663 documentation seems outdated

---

packages/mui-layout/src/components/InsetContainer/InsetContainer.tsx
website/gatsby-config.js
website/package.json
website/src/constants/menus/layoutMenus.js
website/src/global.css
website/src/modules/path/Path.js
website/src/pages/layout/advanced/controlling-sidebar.mdx
website/src/pages/layout/v3/builder.js
yarn.lock

- finish `controlling-sidebar` page
- put builder under v3

#705 advanced layout docs

---

website/src/components/atoms/CodeSandbox.js
website/src/constants/menus/layoutMenus.js
website/src/pages/layout/advanced/dynamic-config.mdx
website/src/templates/DocTemplate.js

docs: ✏️ add dynamic-config manual

---

website/src/constants/menus/layoutMenus.js
website/src/modules/path/Path.js
website/src/pages/layout/api-reference/edge-sidebar-builder.mdx
website/src/pages/layout/api-reference/header-builder.mdx
website/src/pages/layout/api-reference/inset-sidebar-builder.mdx
website/src/pages/layout/api-reference/layout-builder.mdx

docs: ✏️ Layout builder api reference

☄️ Release site v2.0.0-alpha.7

---

website/src/components/layout/IFrame.js
website/src/templates/documentation.css

#721 no styles in firefox

---

package.json
packages/mui-styles/src/select/border/borderSelect.styles.js
packages/mui-styles/src/select/border/index.js
website/package.json
website/src/components/layout/PageLayout.js
website/src/constants/creators.js
website/src/constants/menus/styleMenus.js
website/src/docs/styles/select/border/BorderSelect.js
website/src/docs/styles/select/border/index.js
website/src/docs/styles/select/border/index.md
website/src/docs/styles/select/index.js
website/src/fontawesome.js
website/src/pages/styles/select.js
yarn.lock

Let me know if there are improvements you would like me to make.

#541 border select

---

website/src/constants/menus/layoutMenus.js
website/src/pages/layout/features/auto-collapse.mdx
website/src/pages/layout/features/header-magnet.mdx
website/src/pages/layout/features/persistent-behavior.mdx
website/src/templates/DocTemplate.js
yarn.lock

#718 Layout v4 features documentation

---

package.json
website/src/pages/layout/starters.mdx

docs: ✏️ update NextJS to layout starters

---

packages/mui-styles/src/select/outline/index.js
packages/mui-styles/src/select/outline/outlineSelect.styles.js
website/src/docs/styles/select/outline/OutlineSelect.js
website/src/docs/styles/select/outline/index.js
website/src/docs/styles/select/outline/index.md

This is only one of the 5 designs from this ticket. I will open a separate issue for other designs.

#539 outline select 1

---

packages/mui-styles/src/gutter/row/index.ts
packages/mui-styles/src/gutter/row/rowGutter.styles.ts
website/src/constants/menus/styleMenus.js
website/src/docs/styles/gutter/index.js
website/src/docs/styles/gutter/row/RowGutterStyle.js
website/src/docs/styles/gutter/row/index.js
website/src/docs/styles/gutter/row/index.md
website/src/pages/styles/gutter.js

feat: 🎸 add row gutter styles in util

---

packages/mui-styles/src/iconButton/sized/index.ts
packages/mui-styles/src/iconButton/sized/sizedIconButton.styles.ts
website/src/constants/menus/styleMenus.js
website/src/docs/styles/iconButton/index.js
website/src/docs/styles/iconButton/sized/SizedIconButtonStyle.js
website/src/docs/styles/iconButton/sized/index.js
website/src/docs/styles/iconButton/sized/index.md
website/src/pages/styles/icon-button.js

feat: 🎸 add sized icon button style

---

packages/mui-components/src/button/gmail/GmailButton.js
packages/mui-components/src/button/gmail/GmailButton.stories.js
packages/mui-components/src/button/gmail/GmailButton.test.js
packages/mui-components/src/button/gmail/index.js
website/src/constants/menus/componentMenus.js
website/src/docs/components/button/gmail/GmailButtonDemo.js
website/src/docs/components/button/gmail/index.js
website/src/docs/components/button/gmail/index.md
website/src/docs/components/button/index.js
website/src/pages/components/button.js
website/src/pages/components/button/gmail/index.js

feat: 🎸 add Gmail button component

---

packages/mui-styles/src/avatar/google/googleAvatar.styles.ts
packages/mui-styles/src/avatar/google/index.ts
packages/mui-styles/src/iconButton/sized/sizedIconButton.styles.ts
website/src/constants/menus/styleMenus.js
website/src/docs/styles/avatar/google/GoogleAvatarStyle.js
website/src/docs/styles/avatar/google/index.js
website/src/docs/styles/avatar/google/index.md
website/src/docs/styles/avatar/index.js
website/src/docs/styles/button/avatar/AvatarButtonStyle.js
website/src/docs/styles/button/avatar/index.js
website/src/docs/styles/button/avatar/index.md
website/src/docs/styles/iconButton/sized/SizedIconButtonStyle.js
website/src/pages/styles/avatar.js
website/src/utils/docGen.js

feat: 🎸 add avatar button & google avatar style

---

packages/mui-styles/src/tabs/gmail/gmailTabs.styles.ts
packages/mui-styles/src/tabs/gmail/index.ts
packages/mui-styles/src/tabs/index.ts
website/src/components/organisms/CustomComponentGrid.js
website/src/docs/styles/tabs/gmail/GmailTabsStyle.js
website/src/docs/styles/tabs/gmail/index.js
website/src/docs/styles/tabs/gmail/index.md

feat: 🎸 add GmailTabs style

---

packages/mui-layout/src/contexts/SidebarContext.tsx
packages/mui-layout/src/utils/constant.ts

feat: 🎸 add delay expand action

---

packages/mui-styles/src/listItem/gmail/gmailListItem.styles.ts
packages/mui-styles/src/listItem/gmail/index.ts
website/src/docs/styles/listItem/gmail/GmailListItemStyle.js
website/src/docs/styles/listItem/gmail/index.js
website/src/docs/styles/listItem/gmail/index.md

feat: 🎸 add gmail list item style

---

packages/mui-components/src/sidebarItem/gmail/GmailSidebarItem.tsx
packages/mui-components/src/sidebarItem/gmail/gmailSidebarItem.styles.ts
website/src/docs/styles/collapsibleMenu/gmail/GmailCollapsibleMenuStyle.js
website/src/docs/styles/collapsibleMenu/gmail/index.js
website/src/docs/styles/collapsibleMenu/gmail/index.md

feat: 🎸 add gmail collapsible menu style

---

packages/mui-components/src/menu/arrow/ArrowMenu.stories.js
packages/mui-components/src/menu/arrow/ArrowMenu.test.js
packages/mui-components/src/menu/arrow/ArrowMenu.tsx
packages/mui-components/src/menu/arrow/index.ts
website/src/docs/components/menu/arrow/ArrowMenuDemo.js
website/src/docs/components/menu/arrow/index.js
website/src/docs/components/menu/arrow/index.md
website/src/pages/components/menu/arrow/index.js

feat: 🎸 add ArrowMenu component

---

website/package.json
website/src/containers/Demo/DemoPage.js
website/src/docs/components/card/solidGame/SolidGameCardDemo.js
website/src/docs/components/card/solidGame/index.js
website/src/docs/components/card/solidGame/index.md
website/src/docs/layout/clones/gmail/GmailDemo.js
website/src/pages/components/card/solidGame/index.js
yarn.lock

feat: 🎸 add SolidGameCard component

---

packages/mui-layout/src/builders/EdgeSidebar/EdgeSidebarBuilder.ts
packages/mui-layout/src/contexts/SidebarContext.tsx
packages/mui-layout/src/types/Config.ts
packages/mui-layout/src/utils/sidebarChecker.ts
website/src/constants/menus/layoutMenus.js
website/src/docs/layout/clones/gmail/GmailDemo.js
website/src/pages/layout/api-reference/edge-sidebar-builder.mdx
website/src/pages/layout/features/auto-expanded.mdx
website/src/pages/layout/features/header-magnet.mdx

#854 auto expand config

---

packages/mui-layout/src/builders/EdgeSidebar/EdgeSidebarBuilder.ts
packages/mui-layout/src/components/CollapseBtn/CollapseBtn.tsx
packages/mui-layout/src/components/CollapseIcon/CollapseIcon.tsx
packages/mui-layout/src/components/Content/Content.tsx
packages/mui-layout/src/components/DrawerSidebar/DrawerSidebar.tsx
packages/mui-layout/src/components/EdgeHeaderOffset/EdgeHeaderOffset.tsx
packages/mui-layout/src/components/Footer/Footer.tsx
packages/mui-layout/src/components/Header/Header.tsx
packages/mui-layout/src/components/HeaderOffset/HeaderOffset.tsx
packages/mui-layout/src/components/InsetHeaderOffset/InsetHeaderOffset.tsx
packages/mui-layout/src/components/SidebarTrigger/SidebarTrigger.tsx
packages/mui-layout/src/components/SwipeableSidebar/SwipeableSidebar.tsx
packages/mui-layout/src/hooks/useInsetSidebar.ts
packages/mui-layout/src/utils/createBreakpointStyles.ts
packages/mui-layout/src/utils/resolveDirection.ts
packages/mui-layout/src/utils/utils.spec.ts
website/src/constants/menus/layoutMenus.js
website/src/docs/layout/basicExamples/rtlSupport/RtlSupportDemo.js
website/src/docs/layout/basicExamples/rtlSupport/index.js
website/src/docs/layout/basicExamples/rtlSupport/index.md
website/src/pages/layout/examples/rtl-support.js
website/src/pages/layout/index.mdx

feat: 🎸 support RTL

---

packages/mui-layout/src/components/CollapseBtn/CollapseBtn.tsx
packages/mui-layout/src/components/Content/Content.tsx
packages/mui-layout/src/components/Header/Header.tsx
packages/mui-layout/src/components/InsetSidebar/InsetSidebar.tsx
packages/mui-mockup/src/layout/HeaderEx.js
website/src/constants/menus/layoutMenus.js
website/src/docs/layout/basicExamples/darkTheme/DarkThemeDemo.js
website/src/docs/layout/basicExamples/darkTheme/index.js
website/src/docs/layout/basicExamples/darkTheme/index.md
website/src/pages/layout/examples/dark-theme.js

fix: 🐛 layout components support dark mode

---

packages/mui-components/src/menu/category/CategoryItem.tsx
packages/mui-components/src/menu/category/CategoryProvider.tsx
packages/mui-components/src/menu/category/CategoryTitle.tsx
packages/mui-components/src/menu/category/StylesContext.tsx
packages/mui-components/src/menu/category/defaultStyles.ts
packages/mui-components/src/menu/category/index.ts
packages/mui-styles/src/categoryMenu/mag/index.ts
packages/mui-styles/src/categoryMenu/mag/magCategoryMenu.styles.ts
packages/mui-styles/src/categoryMenu/niki/index.ts
packages/mui-styles/src/categoryMenu/niki/nikiCategoryMenu.styles.ts
website/src/docs/components/menu/category/CategoryMenuDemo.tsx
website/src/docs/components/menu/category/index.md
website/src/docs/components/menu/index.ts
website/src/docs/styles/categoryMenu/index.ts
website/src/docs/styles/categoryMenu/mag/MagCategoryMenuStyle.tsx
website/src/docs/styles/categoryMenu/mag/index.md
website/src/docs/styles/categoryMenu/niki/NikiCategoryMenuStyle.tsx
website/src/docs/styles/categoryMenu/niki/index.md
website/src/pages/styles/category-menu.tsx

#905 category menu

---

packages/mui-components/src/menu/navigation/NavItem.tsx
packages/mui-components/src/menu/navigation/defaultStyles.ts
packages/mui-styles/src/navigationMenu/plain/index.ts
packages/mui-styles/src/navigationMenu/plain/plainNavigationMenu.styles.ts
website/src/constants/menus/componentMenus.js
website/src/constants/menus/styleMenus.js
website/src/docs/components/appFooter/index.ts
website/src/docs/components/appFooter/neptune/NeptuneAppFooterDemo.tsx
website/src/docs/components/appFooter/neptune/index.md
website/src/docs/components/appFooter/ocean/OceanAppFooterDemo.tsx
website/src/docs/components/appFooter/ocean/index.md
website/src/docs/components/menu/navigation/NavigationMenuDemo.tsx
website/src/docs/styles/navigationMenu/index.ts
website/src/docs/styles/navigationMenu/plain/PlainNavigationMenuStyle.tsx
website/src/docs/styles/navigationMenu/plain/index.md
website/src/pages/components/app-footer.tsx
website/src/pages/components/email-subscribe.mdx

add 2 Footer to complex component

#912 Footer I

---

website/src/components/DemoSection/DemoSection.tsx
website/src/docs/components/appFooter/arc/ArcAppFooterDemo.tsx
website/src/docs/components/appFooter/arc/index.md
website/src/docs/components/appFooter/index.ts
website/src/docs/components/appFooter/ocean/OceanAppFooterDemo.tsx
website/src/docs/components/card/showcase/ShowcaseCardDemo.tsx
website/src/docs/components/card/solidGame/SolidGameCardDemo.tsx
website/src/docs/components/card/team/TeamCardDemo.tsx

feat: 🎸 add arcAppFooter & minor fixes

---

website/src/components/DemoSection/DemoSection.tsx

Changed 'hididen' to 'hidden' in line 65.

fix: 🐛 remove typo
